services:
  postgres:
    image: postgres
    container_name: starter-postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - starter_network_postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: starter_network

volumes:
  starter_network_postgres_data:
